<?php

namespace FrontendBundle\Repository;

/**
 * PocketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PocketRepository extends \Doctrine\ORM\EntityRepository
{
}
