<?php

namespace FrontendBundle\Repository;

/**
 * UservoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UservoteRepository extends \Doctrine\ORM\EntityRepository
{
}
