<?php

namespace FrontendBundle\Repository;

/**
 * UsersessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersessionRepository extends \Doctrine\ORM\EntityRepository
{
}
